### ISSUE TITLE
Wireframe Design One

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#1]
1st Wireframe: All on one page, without a next button or skip button. All questions are displayed on the home page, which will submit all questions when the quiz is done at the very end. https://wireframe.cc/5fuHhU
This style of wireframing is not very good for user control, as everything is placed into a single page - when there are many questions, the user will have to scroll back to the top if they want, which is bad user experience for them.
![image](https://user-images.githubusercontent.com/67718063/86304972-9887a780-bc64-11ea-970e-fd482ecfc92c.png)

**Comment by th1095l** [comment]
This wireframe to me looks kind of confusing, which is never a good thing for users, and therefore the usability for the program is not as good because of this confusion, something that makes this wireframe not as useful.

**Comment by BrandonHuang2** [comment]
I don't really like this wireframing choice. It looks like users might have to scroll down a lot, and looks not so good.
