### ISSUE TITLE
Code Design One

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#10]
Design 1: Have a single class, no inheritance, just use class methods and initialization. Each method makes a new frame depending on the type of question and frame.

**Comment by th1095l** [comment]
This design wouldn't be that effective for such ambitious plans for the program, so I would advise against this approach.

**Comment by BrandonHuang2** [comment]
Yeah I agree, although I don't have much programming experience it sounds difficult if it didn't work last year.
