### ISSUE TITLE
Code Design Three

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#11]
Code Design 3 involves the use of Json files to save user data, constant values at the beginning to save aesthetic values, and inheritance from the **Tk.Frame** class rather than the **GUI** class I made. This is far more efficient as it only inherits methods that it needs - external methods can be accessed by `controller.method()`. The Json file enables saving users outside of the main code loop, and having everthing separated also means better future-proofing. It's unneccesary to further improve the code design since this fits all needs for the program I'm developing.

**Comment by th1095l** [comment]
Now this approach is the most sophisticated, and would help improve the functionality of the code as it allows for so many new approaches to be made to programming the quiz.
