### ISSUE TITLE
Font Choices Two

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#12]
My second choice of fonts were two non-serif fonts. Both are monospace fonts: Roboto Mono and Source Code Pro.
![image](https://user-images.githubusercontent.com/67718063/97223171-44688a80-1834-11eb-8454-45c010053b76.png)
![image](https://user-images.githubusercontent.com/67718063/97222752-b4c2dc00-1833-11eb-8f49-57fb203176a6.png)
Roboto Mono would be the header, Source Code Pro the body.

**Comment by th1095l** [comment]
To me, the second font choice looks good, but the 1st one clashes too much and is not as good for maths.

**Comment by BrandonHuang2** [comment]
This looks okay to me.
