### ISSUE TITLE
Font Choices Three

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#13]
For my third choice, I decided on using Roboto (regular) and Montserrat (regular), with Roboto as the header and Montserrat as the body.
![image](https://user-images.githubusercontent.com/67718063/97223341-8265ae80-1834-11eb-9b63-b97b41b9337b.png)
![image](https://user-images.githubusercontent.com/67718063/97223357-85f93580-1834-11eb-849e-54ac03af14bf.png)

**Comment by th1095l** [comment]
I like the second font choice, it seems simple enough to be used nicely with maths. I don't know about the roboto font, but I think it works decently enough for the program.

**Comment by BrandonHuang2** [comment]
I think this pairing looks the best, easiest to read for maths.
