### ISSUE TITLE
Color Choices Two

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#14]
General Theme colour choice.
![image](https://user-images.githubusercontent.com/67718063/93659418-0049d380-fa99-11ea-92fa-5ce531c951a1.png)

**Comment by th1095l** [comment]
These colours do not really strike me as "mathematics" (apart from the light blue), since it's too varied and clashing for the idea of elegant calculus.

**Comment by BrandonHuang2** [comment]
I think this is less clashy, but it still doesn't look very appealing.
