### ISSUE TITLE
Color Choices Three

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#15]
Dark Theme palette choice
![image](https://user-images.githubusercontent.com/67718063/93659217-135ba400-fa97-11ea-86c5-8b7530190831.png)

Light Theme palette choice
![image](https://user-images.githubusercontent.com/67718063/97912012-0f6ab380-1db1-11eb-82ba-e0a552d35d47.png)

**Comment by th1095l** [comment]
Although the dark theme is a bit too brooding for a program with its deep blues, the light palette reminds me of a 'papery' feel, that feels minimalistic and would fit in with the elegance that is calculus.

**Comment by BrandonHuang2** [comment]
This looks better. Easier to read from, less contrast. I would use the dark theme because it's easier on my eyes, but the light theme is good too.
