### ISSUE TITLE
Logo Choice Two

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#16]
Logo two:
The logo is improved as it is less cluttered, and more direct and informative to the user about what the quiz will focus on. The usage of the golden ratio as a holder of calculus ideas gives the user a good impression on what it could be for, even if they don't recognise all of the symbols. It also doesn't have any words, as it uses visuals better to convey the meaning, further improving usability and user experience.
![math-logo](https://user-images.githubusercontent.com/67718063/100493776-50cb6480-319f-11eb-8f3e-d855f0866ade.gif)

**Comment by th1095l** [comment]
Much tidier, contained, and it's easier to see where the logo begins and ends. Also good to get rid of the title, as that's not part of the logo, and therefore this makes it both nicer to look at than the previous (better aesthetics) and the use of mathematical concepts visually establishes a clear connection to mathematics and calculus, and therefore would also help the user understand what it is.

**Comment by BrandonHuang2** [comment]
I like this one. There are a lot of maths 'easter eggs' inside - the golden ratio, pi, i. It looks very 'mathy' to me and makes me think of calculus.
