### ISSUE TITLE
Selection of Questions Choice One

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#17]
The code does not aim to simulate a real exam environment as it is more of a revision quiz, but because it still needs to appeal to a wider audience than just people who are very adept at the subject, some questions must be easier. Therefore, questions are sectioned so that easier questions appear first and harder ones later.

**Comment by BrandonHuang2** [comment]
I like this version better. It's easier on the students.
