### ISSUE TITLE
Font Choices One

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#3]
My first choices for fonts for the header and body texts (UI elements such as menubars count as header text) were Times New Roman and Garamond.
![image](https://user-images.githubusercontent.com/67718063/97222195-db344780-1832-11eb-9287-7e08f5bdf561.png)
![image](https://user-images.githubusercontent.com/67718063/97222225-e4251900-1832-11eb-9e1b-1ed4215bf34d.png)
The header was going to be Times New Roman, and the body Garamond.

**Comment by th1095l** [comment]
> This was a poor choice of fonts, as serif text can be difficult to read. Sans-serif fonts should be used for both the header and the body, and both should have different sizes. However, the body and header should both internally keep the same size. Therefore, I decided to discard this choice.

I agree, this is not a good choice because of these reasons.

**Comment by BrandonHuang2** [comment]
To me, this is not very easy to read. Especially for maths
