### ISSUE TITLE
Choosing Name/Year

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#30]
**This is the introductory page.**
![image](https://user-images.githubusercontent.com/67718063/96056489-35541500-0ee3-11eb-9a0a-0bf347a34b9a.png)

**If the user tries to go to the next page without inputting a name, a warning will appear.**
![image](https://user-images.githubusercontent.com/67718063/96056521-4e5cc600-0ee3-11eb-99b9-b24ff5d2c91b.png)

**The user can select their year level from this dropdown list.**
![image](https://user-images.githubusercontent.com/67718063/96056808-05594180-0ee4-11eb-97ac-4e11f418cf30.png)

**If a name is entered and is valid (numbers, special characters or a name longer than 16 characters will be automatically rejected), the user will go to the selection page.**
![image](https://user-images.githubusercontent.com/67718063/96056555-603e6900-0ee3-11eb-8459-fb703fa4d8ae.png)
![image](https://user-images.githubusercontent.com/67718063/96056623-9380f800-0ee3-11eb-9978-f662c765c811.png)

**Comment by th1095l** [comment]
This code works quite well, seems like a good way to ask the user what their info is.

**Comment by BrandonHuang2** [comment]
This is good! It works well
