### ISSUE TITLE
Choose Sections/Type of Sections

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#31]
**If the user tries to pass the selection page and generate a quiz without anything in it, an error will appear.**
![image](https://user-images.githubusercontent.com/67718063/96057068-9c25fe00-0ee4-11eb-81da-08d04b26425f.png)
![image](https://user-images.githubusercontent.com/67718063/96057122-b65fdc00-0ee4-11eb-8490-ffe06b383f99.png)

**The user can toggle between having sections (so each type of question is in order), or no sections (all questions are randomized).**
![image](https://user-images.githubusercontent.com/67718063/96057179-d5f70480-0ee4-11eb-9b8d-5c2f52d0ec02.png)

**One or more sections can be chosen in any combination.**
![image](https://user-images.githubusercontent.com/67718063/96057241-f4f59680-0ee4-11eb-8bcb-89afb30339e4.png)

**Pressing the start button will generate, and then start the quiz.**
![image](https://user-images.githubusercontent.com/67718063/96057260-06d73980-0ee5-11eb-990a-76cc053b1f7e.png)

**Comment by th1095l** [comment]
Nice and efficient way to alert the user for their info.

**Comment by BrandonHuang2** [comment]
This is quite an efficient method and quite good for if you only want to test certain questions.
