### ISSUE TITLE
Skip/Back Buttons

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#32]
**The user can also opt to skip a question.**
![image](https://user-images.githubusercontent.com/67718063/96057784-33d81c00-0ee6-11eb-96a1-8dbb9d1ee445.png)

**This will register the question as skipped.**
![image](https://user-images.githubusercontent.com/67718063/96057823-46eaec00-0ee6-11eb-876c-fd45be603286.png)

**They can press the back button to head back a question.**
![image](https://user-images.githubusercontent.com/67718063/96057874-6bdf5f00-0ee6-11eb-944c-dc8db0b71e67.png)

**This will not change their answer in any way.**
![image](https://user-images.githubusercontent.com/67718063/96057900-78fc4e00-0ee6-11eb-99b2-a440d5523c1e.png)

**Comment by th1095l** [comment]
An easy way for the user to return to a question and not being forced to answer right away.

**Comment by BrandonHuang2** [comment]
This works well, an important part of any quiz.
