### ISSUE TITLE
Question Buttons

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#34]
**In the quiz, the user can answer a question by pressing their selected answer button.**
![image](https://user-images.githubusercontent.com/67718063/96057579-b7ddd400-0ee5-11eb-87c1-3c9d68fd3cc1.png)

**This brings them to the next question, and registers that question as being answered.**
![image](https://user-images.githubusercontent.com/67718063/96057610-d0e68500-0ee5-11eb-8c3b-d5f076d186d2.png)

**There is no way to tell if the answer chosen was right until the quiz has ended.**

**Comment by th1095l** [comment]
This method works well for the quiz, and is a good use of an easily reversible cyclic framework.

**Comment by BrandonHuang2** [comment]
This is easy to navigate. As a level 3 student, this is great material and framework!
