### ISSUE TITLE
Restart/Quit Buttons

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#35]
**The user can restart the quiz at any time.**
![image](https://user-images.githubusercontent.com/67718063/96058241-38510480-0ee7-11eb-96ab-e055f81ef790.png)

**This brings up the restart confirmation.**
![image](https://user-images.githubusercontent.com/67718063/96058300-5159b580-0ee7-11eb-9d89-d7581b940c44.png)

**All quiz data is removed, but the user is kept the same.**
![image](https://user-images.githubusercontent.com/67718063/96058317-5b7bb400-0ee7-11eb-993b-2b2b01ee3cbc.png)

**They can also quit the program at any time, even at the end or beginning by pressing the quit button. This will delete all data in that instance of the program.**
![image](https://user-images.githubusercontent.com/67718063/96058398-954cba80-0ee7-11eb-8745-fcf11caa92ed.png)

**Comment by th1095l** [comment]
This is good functionality since you can simply restart the quiz and start over instead of quitting and rerunning the program.

**Comment by BrandonHuang2** [comment]
This works well.
