### ISSUE TITLE
Display User Score/Grade

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#36]
**The user will be given a weighted score depending on the difficulty of the question they got right. The number they got correct is also displayed. Harder questions are worth more points. The grade is based on how long the quiz was.**
![image](https://user-images.githubusercontent.com/67718063/96058452-bdd4b480-0ee7-11eb-931d-5761b82bfb54.png)

**The user can also check which of their answers were wrong on the show answers button, and the correct answer.**
![image](https://user-images.githubusercontent.com/67718063/96058519-eceb2600-0ee7-11eb-9071-df2a20fbaa45.png)
![image](https://user-images.githubusercontent.com/67718063/96058545-ff655f80-0ee7-11eb-8b05-b6a087f83733.png)

**Comment by th1095l** [comment]
Wow, an easy way to tell the user their score and stuff. In such a simple way, that would improve the usability of the program, as there isn't much to distract the user from the simple score in front of them. Nice and minimalistic.

**Comment by BrandonHuang2** [comment]
I think this is great for users who want to try an exam simulation kind of thing. It helps when we know what grade we get.
