### ISSUE TITLE
Submit/Store User Score

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#37]
**When the user has completed their quiz, their details are stored in a scoreboard, accessible via the menubar.**
![image](https://user-images.githubusercontent.com/67718063/96058841-d5f90380-0ee8-11eb-8628-8fcd94cff919.png)
![image](https://user-images.githubusercontent.com/67718063/96058860-e315f280-0ee8-11eb-9d53-b4dcec605823.png)

**Users can be removed either by the reset all button, or the remove score button.**
![image](https://user-images.githubusercontent.com/67718063/96058905-fb860d00-0ee8-11eb-87f1-64ae0de95b2d.png)
![image](https://user-images.githubusercontent.com/67718063/96058938-0f317380-0ee9-11eb-90df-a7002bbb7ea0.png)
![image](https://user-images.githubusercontent.com/67718063/96058949-19537200-0ee9-11eb-8670-2f9701d6f94c.png)

**If there is a double-up in a chosen name, a number in brackets (number) is appended to the end of the name.**
![image](https://user-images.githubusercontent.com/67718063/96059015-4b64d400-0ee9-11eb-93a5-ca2842d7e3fe.png)

**Comment by th1095l** [comment]
This functionality is great, especially for users to compare their scores amongst each other. This is a good way of improving the functionality of the program to store scores.

**Comment by BrandonHuang2** [comment]
This feature is an essential one for quizzes. Now I can compete against my friends!
