### ISSUE TITLE
Side Frame

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#38]
**The user can use the side frame to skip between questions. Here, they are skipping to question 11.**
![image](https://user-images.githubusercontent.com/67718063/96058011-c082da00-0ee6-11eb-94a8-398cb1514ba0.png)
![image](https://user-images.githubusercontent.com/67718063/96058026-cb3d6f00-0ee6-11eb-94cc-676fcb6eb163.png)

**It will also display if the user has answered or skipped a question. In order to finish the quiz, all questions have to be answered, otherwise the confirm button is disabled. This means no question can be skipped.**
![image](https://user-images.githubusercontent.com/67718063/96058108-f32cd280-0ee6-11eb-89a3-509530954fcb.png)

**Comment by th1095l** [comment]
Wow, an innovative way for users to select questions instead of moving through, that makes the usability better since users can find it easier to find a question they can do right away and feel less intimidated.

**Comment by BrandonHuang2** [comment]
I like this feature a lot. I can skip to each question without having to cycle through each anymore.
