### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#39]
**The user can opt to make a new user at any time during the program. This erases current user data. It will not work when no current user exists.**
![image](https://user-images.githubusercontent.com/67718063/96201933-5d627780-0fba-11eb-8954-eeef06db742e.png)
![image](https://user-images.githubusercontent.com/67718063/96201985-78cd8280-0fba-11eb-8dad-c31c8c49822e.png)
![image](https://user-images.githubusercontent.com/67718063/96202044-a5819a00-0fba-11eb-8464-15b5bc676c98.png)

**This sends them back to the starting page, and saves the users attempted sections as "Not Attempted" if the new user was made before a section could be selected, and their grade as "Not Achieved", regardless of whether they answered questions or not. It deletes the current user.**
![image](https://user-images.githubusercontent.com/67718063/96202396-89322d00-0fbb-11eb-85db-28a63a76406b.png)

**Comment by th1095l** [comment]
This is a nice functionality that can be used to keep track of scores, especially for an administrator managing student's scores or something.

**Comment by BrandonHuang2** [comment]
This is good. Sometimes my friends want to use the code, but I don't want to save my score.
