### ISSUE TITLE
Color Choices One

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#4]
General Theme
![image](https://user-images.githubusercontent.com/67718063/93659403-e14b4180-fa98-11ea-9f8b-eeb16fa2dc74.png)

**Comment by th1095l** [comment]
Wow, this color palette is all over the place. Does not fit maths, and probably wouldn't fit anything (may mcdonalds, but that's it).

**Comment by BrandonHuang2** [comment]
The colours look too clashy. I would find this hard to read.
