### ISSUE TITLE
Final Version (Version 1.0.0)

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#47]
First Alpha Release Version (stable): [Version 1.0.0.zip](https://github.com/TonySchaufelberger/Python-Calculus-Quiz-Code/files/5633212/Version.1.0.0.zip)

- Functional and Usability testing:
This is the starting frame. Notably, a logo, Maori and an icon have been added.
![image](https://user-images.githubusercontent.com/67718063/100957327-17b83900-357f-11eb-8ffa-36b571e715e4.png)
Pressing "Next" leads to here:
![image](https://user-images.githubusercontent.com/67718063/100957377-30c0ea00-357f-11eb-87f5-9ca63c24c8ea.png)
This shows how tooltips work. Each available box can be checked, and the radio buttons can be swapped.
![image](https://user-images.githubusercontent.com/67718063/100957588-9c0abc00-357f-11eb-8698-4496160b4bd8.png)
The initial frames. Questions can be swapped to immediately by clicking on the buttons on the left. This can also be scrolled. The window automatically becomes larger to fit the left box.
![image](https://user-images.githubusercontent.com/67718063/100957674-c2305c00-357f-11eb-8163-5ed7ad6f310b.png)
This shows how the labels on the left change if you answered or skipped a question.
![image](https://user-images.githubusercontent.com/67718063/100957706-d70cef80-357f-11eb-95ca-a7e867004b7d.png)
All questions must be answered to finish the quiz. This ungreys the "Confirm" button:
![image](https://user-images.githubusercontent.com/67718063/100957764-f60b8180-357f-11eb-957f-e7f5ffe740b9.png)
The final page is here:
![image](https://user-images.githubusercontent.com/67718063/100957783-002d8000-3580-11eb-8763-c2c1c5ccde59.png)
Clicking the "Show Answers" button brings up 
![image](https://user-images.githubusercontent.com/67718063/100957895-2f43f180-3580-11eb-9cd0-3df16635e067.png)
Pressing the "Start Again" button brings the user back to the starting page.

Going into the "Scoreboards" menu button allows you to open the scoreboard window:
![image](https://user-images.githubusercontent.com/67718063/100958234-d9bc1480-3580-11eb-9f04-16bd5fd2d028.png)
Users are saved throughout iterations of the code here, through Json files. These users can be removed by clicking the "Remove User" Button and can be reset by clicking the "Reset All" button.

New Users can be made at any time in the program.
![image](https://user-images.githubusercontent.com/67718063/100958379-14be4800-3581-11eb-8ed0-76e6177cdfb7.png)
This will simply bring the user back to the first page, and save the current user as "Not Achieved".

Experimental features such as "Load User" and "Themes" are disabled:
![image](https://user-images.githubusercontent.com/67718063/100959977-4684de00-3584-11eb-8425-25023e03eb0c.png)

- Valid tests:
![image](https://user-images.githubusercontent.com/67718063/100958510-564ef300-3581-11eb-9b18-e887e83d67da.png)
![image](https://user-images.githubusercontent.com/67718063/100958469-4505e680-3581-11eb-9e09-d306251c9cb4.png)
Showing what happens if the user inputs the same username twice and tries to start a new user without any sections.
![image](https://user-images.githubusercontent.com/67718063/100962166-b09f8200-3588-11eb-853b-a0385551b2ed.png)
If the user presses the "New User" button on the starting page does nothing.
![image](https://user-images.githubusercontent.com/67718063/100962236-d036aa80-3588-11eb-911f-76d51545ee9d.png)
Pressing the "Quit" button brings up the confirmation popup.
![image](https://user-images.githubusercontent.com/67718063/100962299-efcdd300-3588-11eb-82de-91d8af0b8d9e.png)
Pressing the "Restart" Button also brings up a popup. This redirects the user back to the selection page without changing anything.
- Invalid tests:
![image](https://user-images.githubusercontent.com/67718063/100958863-ff95e900-3581-11eb-943e-b4e9ba816642.png)
This shows how a name must be input for the code to run. Also, letters and special characters cannot be input.
![image](https://user-images.githubusercontent.com/67718063/100957452-53530300-357f-11eb-9915-28fb86fa398b.png)
This shows how a question type must be chosen for the quiz to generate and start.
- Boundary tests:
![image](https://user-images.githubusercontent.com/67718063/100958713-b5146c80-3581-11eb-978c-a69a5ba9d269.png)
Showing parameters for different grades decided by boundaries (although this is generatively determined depending on how long the quiz is, so exact values can't be defined).
![image](https://user-images.githubusercontent.com/67718063/100958819-eab95580-3581-11eb-938c-3c368862c4b4.png)
Proof of boundary tests.

The final version has filled many of the holes that the past versions had, including the adding of a tooltip to make instructions clearer, and cultural considerations by adding Maori. It has finally incorporated a logo as the defining feature of the code, and everything is conventional. This improved the usability and cultural implications of the program as users can now more easily identify the program, and can more easily navigate through it. It also reduces the chances of them breaking the code by deisabling experimental features. Culturally, the incorporation of Maori improved cultural considerations by recognizing and accepting the culture into the program. Aesthetics could be improved further, but it is suitable for this version as the program is designed to purely set out questions and have students test themselves as a revision program.

To improve this release version further, more question formats (such as questions with an image, drawing questions, questions with an input or questions with dropdown lists) should be supported, in order to enhance the quiz experience and increase the breadth of content allowed for the quiz. Requested features, such as the dark theme and loading past users directly, should also be implemented (both of which were previously experimental).
The point of this first release was to demonstrate and release the framework to see how users react and respond to the release. This is to prepare it for the first Beta release, which will be released for an open beta (rather than the current closed beta). Therefore the full questions will also need to be added, but currently this is not an issue for version 1.0.0 (with the current questions).

**Comment by BrandonHuang2** [comment]
This is looking great so far! I think it's smart to release it first as an alpha version, see what others say first before acting on it. I personally think aesthetics and layout need some more work, and I'd like to see the dark themes back too! More diversity in questions asked would also make it more fun and engaging to work with. I'm very interested to see where this goes.

**Comment by th1095l** [comment]
That's a lot of good stuff... Good work. I second what Brandon suggested.
