### ISSUE TITLE
Selection of Questions Choice Two

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#5]
The questions need to be difficult enough to copy what the real exams will be like. There are no variations in difficulty (all of them are hard) because it is a test for revising for exams specifically, so it needs to prepare the user for them.

**Comment by BrandonHuang2** [comment]
This version sounds a little hard... especially for someone who is not so good at calculus and I want to revise the basics.
