### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#57]
Conclusion

Did the outcome meet your specification?
From post-evaluating my outcome, I think it met my specifications. The program looks and feels minimalistic, and like a math quiz, and does not have any loud colours or strange design choices. It has an abundance of features designed to improve user experience, which are all optional but effective (such as score saving, quiz generating). While I would have preferred to complete the experimental features, requested by some users, time constraints prevented me from completing them. However, the most important, core parts of the program have been completed and this it the important part. Therefore, the program has achieved its purpose of being an in-depth, user-focused quiz revision program.

How does planning, trailing and testing create a fully functional program?
Planning, trailing and testing create a fully functional program by making sure that there is extensive bug-testing and quality insurance for functionality, as testing eliminates any hidden problems in the code. Trialing makes sure the components used are appropriate for the intent of the design, and is accepted by users, as well as offering multiple options for a purpose. Planning helps cover everything the program might need, fully considering the functionality.

Planning, trailing and testing
I planned my program by using github to use the 'projects' feature to create issues as a checklist and planning feature, as well as having due dates. The components were mostly trialed from previous programs, which have already proven to been effective therefore enhancing the program as a result. Other components were decided by discussion with users. The program was finally rigorously tested by users and myself, to valid, invalid and boundary test all parts of the program to make sure the program was fully functional.

Areas you found difficult?
An area I found difficult was creating a good looking program which incorporated an effective palette and logo, as well as adding questions to the code. This was because of the lack of support for these features in Tkinter. Another area I found difficult was learning entire new skills for the code - in the long run, this greatly benefited the program as it allowed functional features like score saving.

Areas needed for further development?
Areas for further development in the code is to fix the experimental features, complete and expand the question lists, and improve the aesthetic designs.

Did you meet all deadlines?
I met nearly all deadlines - some were completed before the deadline, and others were completed overdue. I also was not strict enough with user feedback, as I did not ask enough for user commentary on new features. Next time, I need to be more efficient and plan more for the timeframe for each task in order to complete deadlines.

**Comment by BrandonHuang2** [comment]
I found that many of my users echoed my thoughts on future aesthetic improvements. That will be my primary goal for future updates of the program.

**Comment by TonySchaufelberger** [comment]
I found that many of my users echoed my thoughts on future aesthetic improvements. That will be my primary goal for future updates of the program.
