### ISSUE TITLE
Purpose of the Interactive Quiz

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#6]
This is an NCEA Level 3 Calculus revision quiz, designed for the user to practice their calculus skills. Thus, the questions need to be difficult to copy what the real exams will be like. Questions are from all externals in sections, in random order, so that the user can practice each one by one. However, they can choose which sections they want to revise, and whether they want to do it all together or separately. This is important for the user as it fulfills the end-user goals, as if the quiz is too easy, then there is no point to the quiz as the user won't be getting anything of value from it. However, if the questions are too hard, the user won't be able to answer any and may be discouraged. Therefore the right level of questions are required - these are the same types of questions used in the exams. This improves user experience by allowing users to effectively revise their calculus.

**Comment by BrandonHuang2** [comment]
This is good. I think it is a good purpose for what we are learning.
