### ISSUE TITLE
Logo Choice One

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#7]
Logo one: this logo is colorful, but cluttered as it has many images squeezed into it. There are also many colors, and the logo isn't unique as it is only some words and mathematical symbols. This means it does not have a strong identity with the program. This is poor user experience the user will have an incorrect first impression of the program, and it will be more difficult for them to associate the program with the logo.
![calculus-logo](https://user-images.githubusercontent.com/67718063/86305111-fcaa6b80-bc64-11ea-9bc9-014e89e7ccc8.png)

**Comment by th1095l** [comment]
This logo is all over the place... It's not contained in any way, and it's kind laterally stretched too much. That would make it confusing to the user what exactly your logo is, and therefore would also decrease the accessibility and usability of the code, as they would be confused as to where to look for, and confusion is never a good thing.

**Comment by BrandonHuang2** [comment]
I don't really like this logo. It looks clunky and disorganized.
