### ISSUE TITLE
Wireframe Design Two

### ISSUE THREAD

**Issue by TonySchaufelberger** [TonySchaufelberger/Python-Calculus-Quiz-Code#9]
2nd Wireframe: Each question will have it's own frame, and will go to the next question when the answer is selected. The question can be skipped, which is automatically a wrong answer - that button is on the bottom right. There is a back button which takes the user back a question to redo it. There is also an exit button at the bottom, where the user can start again. In the first frame, the user can select which sections they want to revise, and whether they want to do it all together or in separate sections. Also, each question page has its own list of questions answered or unanswered, which allows the user to skip to it. There are popup windows for additional features (scoreboard, dialog boxes).
Wireframe for start page: https://wireframe.cc/gitksO
![image](https://user-images.githubusercontent.com/67718063/96203572-bb915980-0fbe-11eb-9341-38668265d2e4.png)

Wireframe for selection page: https://wireframe.cc/U0nVj0
![image](https://user-images.githubusercontent.com/67718063/96204388-aa494c80-0fc0-11eb-905e-c99fd4d2efff.png)

The wireframe for each question: https://wireframe.cc/yrRCWt
![image](https://user-images.githubusercontent.com/67718063/96203412-4c1b6a00-0fbe-11eb-9077-380618c64125.png)

The wireframe for the ending page: https://wireframe.cc/MkFS5W
![image](https://user-images.githubusercontent.com/67718063/96204107-f2b43a80-0fbf-11eb-8979-1c78fba1ace9.png)

Wireframe for scoreboard: https://wireframe.cc/FpM1Wy
![image](https://user-images.githubusercontent.com/67718063/96204355-956cb900-0fc0-11eb-978a-dc17eb3cec09.png)

**Comment by th1095l** [comment]
This code looks a lot more clear cut than the previous choice, therefore it is already better, since it's more clear and therefore the usability is better, so it''s a good choice.

**Comment by BrandonHuang2** [comment]
I think splitting each question and part into it's own page is more effective and looks better than the other one.
